### ISSUE TITLE
I have problem with .in domain statics

### ISSUE THREAD

**Issue by MobrilzCom** [domaindumper/domain-statistics#5]
When i use your API End Like this: https://api.domaindumper.com/database/stats/1990/01/01/stats.json

but it's not sowing for .in statices.

Please help

**Comment by ProgrammerNomad** [comment]
hello,

Just wait we need to rebuild because some how build has been failed that why its not working. but now its redeploy completed so you can access it.

Thanks

**Comment by MobrilzCom** [comment]
OK great now its working 👍
